program not_not;

var res: boolean;

function not_not (): boolean;
begin
	not_not :=
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	not not not not not not not not not not not not not not not not
	true;
end;


begin
	res := not_not();

	writeln(res);
end.
