extends Control

func _ready() -> void:
	print(notnot())

func notnot() -> bool:
	return not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not \

	true
