import sys  
 
def notnot():
	return not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not not not not not not not not not not not not \
	not not not not not  \
	True



print(notnot())



